"""Role anchors, reachability maps, and versioned state vectors."""

from .anchors import (
    AircraftResourceAnchor,
    FlowAnchor,
    LeaderFollowerAnchor,
    ResourceAnchors,
    SegmentAnchorSet,
    ResourceETAQuery,
    SimulatorFlightPrediction,
    active_resource_predictions,
    build_current_segment_anchors,
    build_resource_anchors,
    build_resource_anchors_from_query,
    order_flights_by_eta,
    resource_eta_s,
    resource_station_m,
)
from .minimum_time import (
    LocalReachabilityQuery,
    ReachabilityMap,
    compute_reachability_map,
    earliest_resource_eta_s,
    reachability_from_query,
    simulator_reachability_map,
)
from .schema import FeatureField, FeatureSchema, FeatureVector, leader_follower_feature_schema
from .state_vector import (
    CommitmentComponents,
    LeaderFollowerFeatureInputs,
    LeaderFollowerStateQuery,
    commitment_components,
    derive_leader_follower_state_vector,
    pressure_in_half_open_window,
    simulator_flight_commitment_components,
    simulator_state_vector,
    state_vector_from_query,
)

__all__ = [
    "AircraftResourceAnchor",
    "CommitmentComponents",
    "FeatureField",
    "FeatureSchema",
    "FeatureVector",
    "FlowAnchor",
    "LeaderFollowerAnchor",
    "LeaderFollowerFeatureInputs",
    "LeaderFollowerStateQuery",
    "LocalReachabilityQuery",
    "ReachabilityMap",
    "ResourceAnchors",
    "SegmentAnchorSet",
    "ResourceETAQuery",
    "SimulatorFlightPrediction",
    "active_resource_predictions",
    "build_current_segment_anchors",
    "build_resource_anchors",
    "build_resource_anchors_from_query",
    "commitment_components",
    "compute_reachability_map",
    "derive_leader_follower_state_vector",
    "earliest_resource_eta_s",
    "leader_follower_feature_schema",
    "order_flights_by_eta",
    "pressure_in_half_open_window",
    "reachability_from_query",
    "resource_eta_s",
    "resource_station_m",
    "simulator_reachability_map",
    "simulator_flight_commitment_components",
    "simulator_state_vector",
    "state_vector_from_query",
]
