from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from openap import aero

from .config import AircraftConfig, ModeConfig
from .openap_adapter import (
    OpenAPAircraftData,
    OpenAPObjects,
    extract_aircraft_data,
    load_openap,
    wrap_default,
)
from .units import fpm_to_mps, ft_to_m, mps_to_kts


def _default_vs_1g_ref_cas_mps(*, target_cas_mps: float, factor: float) -> float:
    """Derive a conservative reference CAS for 1g stall-margin estimates.

    The returned value is the target CAS divided by a safety factor, with a
    floor of 1 m/s so downstream calculations never see a zero or negative
    reference speed.

    Parameters
    ----------
    target_cas_mps:
        The target calibrated airspeed in m/s, usually taken from an OpenAP
        speed schedule.
    factor:
        Safety factor used to back off from the target speed.

    Returns
    -------
    float
        The reduced reference CAS in m/s.

    Examples
    --------
    >>> _default_vs_1g_ref_cas_mps(target_cas_mps=90.0, factor=1.8)
    50.0
    >>> _default_vs_1g_ref_cas_mps(target_cas_mps=0.4, factor=2.0)
    1.0

    Nuance
    -------
    This is not an observed stall speed. It is a calibration convenience used
    when building the bank-angle limits in `build_default_aircraft_config`.
    """
    return max(1.0, target_cas_mps / factor)


@dataclass(frozen=True)
class PolarFitResult:
    cd0: float
    k: float


def suggest_approach_mass_kg(aircraft_data: OpenAPAircraftData, payload_kg: float) -> float:
    """Suggest a landing/approach mass from OpenAP airframe data and payload.

    The function chooses the lesser of maximum landing weight and
    operating-empty-weight plus payload. This gives a practical mass for
    approach calibration without assuming the aircraft is loaded beyond its
    landing limit.

    Parameters
    ----------
    aircraft_data:
        Aircraft metadata extracted from OpenAP.
    payload_kg:
        Payload contribution in kilograms.

    Returns
    -------
    float
        The suggested approach mass in kilograms.

    Examples
    --------
    If `mlw_kg=73_000` and `oew_kg=42_000`, then a `12_000` kg payload yields
    `54_000` kg:

    >>> suggest_approach_mass_kg(aircraft_data, payload_kg=12_000.0)
    54000.0

    If the payload would exceed the landing limit, the result is capped at
    `73_000` kg:

    >>> suggest_approach_mass_kg(aircraft_data, payload_kg=40_000.0)
    73000.0

    Nuance
    -------
    This helper is intentionally conservative. It is meant to produce a
    calibration mass that is realistic for approach and final-mode drag
    fitting, not a nominal dispatch weight.
    """
    return min(aircraft_data.mlw_kg, aircraft_data.oew_kg + payload_kg)


def _fit_effective_polar(
    drag_samples_newtons: np.ndarray,
    tas_mps: np.ndarray,
    alt_m: np.ndarray,
    vs_mps: np.ndarray,
    mass_kg: float,
    wing_area_m2: float,
) -> PolarFitResult:
    """Fit a simple parabolic drag polar to sampled drag observations.

    The function converts each sample into a normalized drag observation and
    a corresponding lift coefficient, then solves the least-squares system for
    `cd0` and `k` in the model `CD = cd0 + k * CL^2`.

    Parameters
    ----------
    drag_samples_newtons:
        Sampled drag forces from OpenAP or another reference model.
    tas_mps:
        True airspeed for each sample in m/s.
    alt_m:
        Pressure altitude for each sample in meters.
    vs_mps:
        Vertical speed for each sample in m/s.
    mass_kg:
        Aircraft mass used to infer lift.
    wing_area_m2:
        Wing reference area.

    Returns
    -------
    PolarFitResult
        The fitted zero-lift drag coefficient and induced-drag factor.

    Examples
    --------
    If the input data were generated by an exact polar
    `CD = 0.020 + 0.050 * CL^2`, then the fit returns
    `PolarFitResult(cd0=0.02, k=0.05)`.

    In practice the samples are noisy, so the fitted coefficients are the
    least-squares best approximation rather than exact generator parameters.

    Nuance
    -------
    The fit is intentionally simple and mode-specific. It is used as a local
    approximation of approach/final drag behavior, not a full aerodynamic
    identification pipeline.
    """
    rows: list[list[float]] = []
    targets: list[float] = []

    for drag_newtons, v_tas_mps, h_m, v_speed_mps in zip(
        drag_samples_newtons,
        tas_mps,
        alt_m,
        vs_mps,
        strict=True,
    ):
        _, rho, _ = aero.atmos(float(h_m), dT=0.0)
        dynamic_pressure = 0.5 * float(rho) * float(v_tas_mps) ** 2
        sin_gamma = float(np.clip(float(v_speed_mps) / max(float(v_tas_mps), 1.0), -0.95, 0.95))
        lift_newtons = mass_kg * aero.g0 * float(np.cos(np.arcsin(sin_gamma)))
        cl = lift_newtons / max(dynamic_pressure * wing_area_m2, 1e-6)
        rows.append([1.0, cl**2])
        targets.append(float(drag_newtons) / max(dynamic_pressure * wing_area_m2, 1e-6))

    design = np.asarray(rows, dtype=float)
    observations = np.asarray(targets, dtype=float)
    coeffs, _, _, _ = np.linalg.lstsq(design, observations, rcond=None)
    return PolarFitResult(cd0=float(coeffs[0]), k=float(coeffs[1]))


def fit_mode_polar_from_openap(
    openap: OpenAPObjects,
    aircraft_data: OpenAPAircraftData,
    mass_kg: float,
    *,
    flap_angle_deg: float,
    landing_gear: bool,
    tas_kts_grid: np.ndarray,
    alt_ft_grid: np.ndarray,
    vs_fpm: float,
) -> PolarFitResult:
    """Fit a mode-specific drag polar by sampling OpenAP's non-clean model.

    This helper samples OpenAP drag over a TAS/altitude grid for a specific
    flap and gear configuration, converts the samples to SI units, and then
    feeds them into `_fit_effective_polar`.

    Parameters
    ----------
    openap:
        Loaded OpenAP object bundle.
    aircraft_data:
        Extracted aircraft metadata, used for wing area and other reference
        values.
    mass_kg:
        Aircraft mass used during the sampling sweep.
    flap_angle_deg:
        Flap setting passed to OpenAP.
    landing_gear:
        Whether landing gear is extended during sampling.
    tas_kts_grid:
        Grid of true airspeed values in knots.
    alt_ft_grid:
        Grid of altitude values in feet.
    vs_fpm:
        Vertical speed used in the OpenAP drag query.

    Returns
    -------
    PolarFitResult
        The fitted drag coefficients for the sampled configuration.

    Examples
    --------
    For a small calibration sweep:

    >>> fit = fit_mode_polar_from_openap(
    ...     openap=openap,
    ...     aircraft_data=aircraft_data,
    ...     mass_kg=65_000.0,
    ...     flap_angle_deg=15.0,
    ...     landing_gear=False,
    ...     tas_kts_grid=np.asarray([140.0, 160.0]),
    ...     alt_ft_grid=np.asarray([2_000.0, 4_000.0]),
    ...     vs_fpm=-700.0,
    ... )

    A synthetic dataset that follows `CD = 0.030 + 0.060 * CL^2` would produce
    `PolarFitResult(cd0=0.03, k=0.06)`.

    Nuance
    -------
    The result depends on the aircraft type, the selected OpenAP engine data,
    and the exact grid. It is designed for coarse calibration during config
    construction, not for high-fidelity aerodynamic identification.
    """
    samples_drag: list[float] = []
    samples_tas_mps: list[float] = []
    samples_alt_m: list[float] = []
    samples_vs_mps: list[float] = []

    for tas_kts in tas_kts_grid:
        for alt_ft in alt_ft_grid:
            drag_newtons = float(
                openap.drag.nonclean(
                    mass=mass_kg,
                    tas=float(tas_kts),
                    alt=float(alt_ft),
                    flap_angle=float(flap_angle_deg),
                    vs=float(vs_fpm),
                    landing_gear=landing_gear,
                )
            )
            samples_drag.append(drag_newtons)
            samples_tas_mps.append(float(tas_kts) * aero.kts)
            samples_alt_m.append(ft_to_m(float(alt_ft)))
            samples_vs_mps.append(fpm_to_mps(float(vs_fpm)))

    return _fit_effective_polar(
        drag_samples_newtons=np.asarray(samples_drag, dtype=float),
        tas_mps=np.asarray(samples_tas_mps, dtype=float),
        alt_m=np.asarray(samples_alt_m, dtype=float),
        vs_mps=np.asarray(samples_vs_mps, dtype=float),
        mass_kg=mass_kg,
        wing_area_m2=aircraft_data.wing_area_m2,
    )


def build_default_aircraft_config(
    typecode: str,
    mass_kg: float,
    *,
    engine_name: str | None = None,
    openap_objects: OpenAPObjects | None = None,
    approach_gate_m: float = 35_000.0,
    final_gate_m: float = 12_000.0,
    k_h_sinv: float = 0.03,
    a_acc_max_mps2: float = 0.8,
) -> tuple[AircraftConfig, OpenAPObjects]:
    """Build the default aircraft configuration and its backing OpenAP bundle.

    This is the main calibration entrypoint used by the fixtures and examples.
    It loads OpenAP data if necessary, fits approach and final drag polars, and
    assembles a complete `AircraftConfig` with mode-specific limits.

    Parameters
    ----------
    typecode:
        Aircraft type code passed to OpenAP.
    mass_kg:
        Calibration mass used for the drag fits and reference configuration.
    engine_name:
        Optional engine selection forwarded to OpenAP.
    openap_objects:
        Optional preloaded OpenAP bundle. Supplying this avoids reloading the
        same aircraft data in tests or repeated setup code.
    approach_gate_m:
        Along-track distance at which approach mode starts.
    final_gate_m:
        Along-track distance at which final mode starts.
    k_h_sinv:
        Altitude tracking gain used by the longitudinal controller.
    a_acc_max_mps2:
        Maximum acceleration allowed by the longitudinal controller.

    Returns
    -------
    tuple[AircraftConfig, OpenAPObjects]
        The calibrated configuration and the OpenAP objects used to build it.

    Examples
    --------
    >>> cfg, openap = build_default_aircraft_config("A320", mass_kg=65_000.0)
    >>> cfg.typecode
    'A320'
    >>> cfg.final.name
    'final'

    If a specific engine is requested, the selected metadata is preserved:

    >>> cfg, _ = build_default_aircraft_config("A320", mass_kg=65_000.0, engine_name="V2527-A5")
    >>> cfg.engine_name
    'V2527-A5'

    Nuance
    -------
    The returned configuration is calibrated for simulation convenience. The
    fitted polars are deliberately lightweight approximations of approach and
    final behavior, and the gate distances control when the simulator switches
    between clean, approach, and final modes.
    """
    openap = openap_objects or load_openap(typecode, engine_name=engine_name)
    aircraft_data = extract_aircraft_data(openap)
    wrap = openap.wrap

    final_vcas_kts = mps_to_kts(wrap_default(wrap, "finalapp_vcas"))
    landing_vcas_kts = mps_to_kts(wrap_default(wrap, "landing_speed"))

    approach_fit = fit_mode_polar_from_openap(
        openap,
        aircraft_data,
        mass_kg,
        flap_angle_deg=15.0,
        landing_gear=False,
        tas_kts_grid=np.linspace(max(140.0, final_vcas_kts + 10.0), 190.0, 6),
        alt_ft_grid=np.linspace(1_500.0, 6_000.0, 6),
        vs_fpm=-700.0,
    )
    final_fit = fit_mode_polar_from_openap(
        openap,
        aircraft_data,
        mass_kg,
        flap_angle_deg=30.0,
        landing_gear=True,
        tas_kts_grid=np.linspace(max(120.0, landing_vcas_kts), max(145.0, final_vcas_kts + 5.0), 6),
        alt_ft_grid=np.linspace(0.0, 3_000.0, 6),
        vs_fpm=-650.0,
    )

    clean = ModeConfig(
        name="clean",
        tau_v_s=18.0,
        vs_min_mps=float(openap.wrap.descent_vs_concas()["minimum"]),
        vs_max_mps=3.0,
        cd0=aircraft_data.clean_cd0,
        k=aircraft_data.clean_k,
        phi_comfort_max_rad=np.deg2rad(25.0),
        phi_procedure_max_rad=np.deg2rad(25.0),
        tau_phi_s=2.0,
        p_max_rps=np.deg2rad(6.0),
        vs_1g_ref_cas_mps=_default_vs_1g_ref_cas_mps(
            target_cas_mps=wrap_default(wrap, "descent_const_vcas"),
            factor=1.8,
        ),
        cas_max_mps=aircraft_data.vmo_kts * aero.kts,
    )
    approach = ModeConfig(
        name="approach",
        tau_v_s=22.0,
        vs_min_mps=float(openap.wrap.descent_vs_post_concas()["minimum"]),
        vs_max_mps=2.0,
        cd0=approach_fit.cd0,
        k=approach_fit.k,
        phi_comfort_max_rad=np.deg2rad(22.0),
        phi_procedure_max_rad=np.deg2rad(20.0),
        tau_phi_s=2.5,
        p_max_rps=np.deg2rad(5.0),
        vs_1g_ref_cas_mps=_default_vs_1g_ref_cas_mps(
            target_cas_mps=wrap_default(wrap, "finalapp_vcas"),
            factor=1.3,
        ),
        cas_min_mps=wrap_default(wrap, "finalapp_vcas"),
        cas_max_mps=wrap_default(wrap, "descent_const_vcas"),
    )
    final = ModeConfig(
        name="final",
        tau_v_s=25.0,
        vs_min_mps=float(openap.wrap.finalapp_vs()["minimum"]),
        vs_max_mps=1.0,
        cd0=final_fit.cd0,
        k=final_fit.k,
        phi_comfort_max_rad=np.deg2rad(18.0),
        phi_procedure_max_rad=np.deg2rad(15.0),
        tau_phi_s=3.0,
        p_max_rps=np.deg2rad(4.0),
        vs_1g_ref_cas_mps=_default_vs_1g_ref_cas_mps(
            target_cas_mps=wrap_default(wrap, "landing_speed"),
            factor=1.23,
        ),
        cas_min_mps=wrap_default(wrap, "landing_speed"),
        cas_max_mps=wrap_default(wrap, "finalapp_vcas"),
    )

    cfg = AircraftConfig(
        typecode=typecode,
        engine_name=aircraft_data.engine_name,
        mass_kg=mass_kg,
        reference_mass_kg=aircraft_data.mlw_kg,
        wing_area_m2=aircraft_data.wing_area_m2,
        vmo_kts=aircraft_data.vmo_kts,
        mmo=aircraft_data.mmo,
        clean=clean,
        approach=approach,
        final=final,
        k_h_sinv=k_h_sinv,
        a_acc_max_mps2=a_acc_max_mps2,
        final_gate_m=final_gate_m,
        approach_gate_m=approach_gate_m,
    )
    return cfg, openap
